<?php

namespace atn\AnimalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceAnimalRepository extends EntityRepository
{
    
}
