atn_media:
    resource: "@atnMediaBundle/Resources/config/routing.yml"
    prefix:   /

atn_main:
    resource: "@atnMainBundle/Resources/config/routing.yml"
    prefix:   /

atn_animal:
    resource: "@atnAnimalBundle/Resources/config/routing.yml"
    prefix:   /animal

atn_user:
    resource: "@atnUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

