<?php

namespace atn\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
     public function getLastCommentairesByMedia($media,$offset = 0,$number = 5) {
        $query = $this->createQueryBuilder('c')
                        ->where('c.media = :media')
                        ->orderBy('c.dateCreate','desc')
                        ->setFirstResult($offset)
                        ->setMaxResults($number)
                        ->setParameter('media',$media )
                        ->getQuery()->getResult();
        return array_reverse($query);
    }
}
